api:
  host: '127.0.0.1'
  port: 5002
  path: '/transcribe/v1'
  data_dir: '/home/core/llm/chatbot/data'
  gpu_lock_file: 'RTX_4090_1.lock'
  huggingface_token: ''
client:
  timeout: 1800
  uri: 'http://127.0.0.1:3000/sebastian/api/v1'
  user_agent: 'Sebastian/0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
  pub_key: ''
  priv_key: ''
